### ISSUE TITLE
segfault in test suite with 7.4.0-dev

### ISSUE THREAD

**Issue by remicollet** [krakjoe/cmark#17]
```
TEST 108/268 [tests/Node/BulletList/009.phpt]
========DIFF========
001+ Termsig=11
001- bool(false)
002- bool(true)
========DONE========
FAIL CommonMark\Node\BulletList cached write tight [tests/Node/BulletList/009.phpt] 

TEST 110/268 [tests/Node/BulletList/011.phpt]
========DIFF========
001+ Termsig=11
001- int(1)
002- int(2)
========DONE========
FAIL CommonMark\Node\BulletList cached write delimiter [tests/Node/BulletList/011.phpt] 

TEST 139/268 [tests/Node/Custom/004.phpt]
========DIFF========
001+ Termsig=11
001- string(2) "OK"
002- string(2) "KO"
========DONE========
FAIL CommonMark\Node\Custom cached write onEnter [tests/Node/Custom/004.phpt] 

TEST 140/268 [tests/Node/Custom/005.phpt]
========DIFF========
001+ Termsig=11
001- string(2) "OK"
002- string(2) "KO"
========DONE========
FAIL CommonMark\Node\Custom cached write onLeave [tests/Node/Custom/005.phpt] 

TEST 182/268 [tests/Node/Heading/008.phpt]
========DIFF========
001+ Termsig=11
001- int(1)
002- int(2)
========DONE========
FAIL CommonMark\Node\Heading cached write [tests/Node/Heading/008.phpt] 

TEST 207/268 [tests/Node/Media/011.phpt]
========DIFF========
001+ Termsig=11
001- string(2) "OK"
002- string(2) "KO"
========DONE========
FAIL CommonMark\Node\Media write cached title [tests/Node/Media/011.phpt] 

TEST 208/268 [tests/Node/Media/012.phpt]
========DIFF========
001+ Termsig=11
001- string(2) "OK"
002- string(2) "KO"
========DONE========
FAIL CommonMark\Node\Media write cached url [tests/Node/Media/012.phpt] 

TEST 226/268 [tests/Node/OrderedList/007.phpt]
========DIFF========
001+ Termsig=11
001- OK
========DONE========
FAIL CommonMark\Node\OrderedList write cached start [tests/Node/OrderedList/007.phpt] 

TEST 239/268 [tests/Node/Text/007.phpt]
========DIFF========
001+ Termsig=11
001- string(2) "OK"
002- string(2) "KO"
========DONE========
FAIL CommonMark\Node\Text cached write [tests/Node/Text/007.phpt] 

```

**Comment by remicollet** [comment]
Hmm... don't know if this is php or cmark fault

```
(gdb) bt
#0  0x0000555555877c3c in ZEND_ASSIGN_OBJ_SPEC_CV_CONST_OP_DATA_CV_HANDLER () at /usr/src/debug/php74-php-7.4.0~DEV.20190521-2.fc29.remi.x86_64/Zend/zend_vm_execute.h:43167
#1  0x000055555588e2e6 in execute_ex (ex=0x7ffff6e7d140) at /usr/src/debug/php74-php-7.4.0~DEV.20190521-2.fc29.remi.x86_64/Zend/zend_vm_execute.h:64433
#2  0x0000555555896d2e in zend_execute (op_array=op_array@entry=0x7ffff6e863c0, return_value=return_value@entry=0x7ffff6e14180)
    at /usr/src/debug/php74-php-7.4.0~DEV.20190521-2.fc29.remi.x86_64/Zend/zend_vm_execute.h:65726
#3  0x000055555580455b in zend_execute_scripts (type=type@entry=8, retval=0x7ffff6e14180, retval@entry=0x0, file_count=file_count@entry=3)
    at /usr/src/debug/php74-php-7.4.0~DEV.20190521-2.fc29.remi.x86_64/Zend/zend.c:1661
#4  0x00005555557a4010 in php_execute_script (primary_file=<optimized out>) at /usr/src/debug/php74-php-7.4.0~DEV.20190521-2.fc29.remi.x86_64/main/main.c:2676
#5  0x00005555558993bf in do_cli (argc=64, argv=0x555555a29420) at /usr/src/debug/php74-php-7.4.0~DEV.20190521-2.fc29.remi.x86_64/sapi/cli/php_cli.c:985
#6  0x0000555555668ae2 in main (argc=64, argv=0x555555a29420) at /usr/src/debug/php74-php-7.4.0~DEV.20190521-2.fc29.remi.x86_64/sapi/cli/php_cli.c:1375

```

**Comment by krakjoe** [comment]
Hi @remicollet, tip of develop has been prepared for 7.4, so closing this ...
